---
# - name: 'Make a new workspace directory'
#   ansible.builtin.file:
#     state: directory
#     path: ./cdk_workspace

# - name: 'Run cdk init app -l python'
#   ansible.builtin.shell:
#     cmd: "cdk init app -l python"
#     chdir: "cdk_workspace"
#   changed_when: false
#   register: _init_results
#   failed_when: "_init_results.rc > 0"

# - name: 'Install dependencies'
#   ansible.builtin.shell: "{{ item }}"
#   changed_when: false
#   loop:
#     - "python -m pip install --upgrade pip"
#     - "python -m pip install -r cdk_workspace/requirements.txt"

- name: 'Template out the cdk workspace stack files into place'
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: '0644'
    force: true
  loop:
    - { "src": "cdk_workspace_stack.py.j2", "dst": "cdk_workspace/cdk_workspace/cdk_workspace_stack.py" }
    - { "src": "vpn_stack.py.j2", "dst": "cdk_workspace/cdk_workspace/vpn_stack.py" }
    - { "src": "app.py.j2", "dst": "cdk_workspace/app.py" }

# - name: 'Run cdk deploy --- There will be a delay up to 5 minutes before there is output...'
#   ansible.builtin.shell:
#     cmd: "cdk deploy --require-approval never"
#     chdir: "cdk_workspace"
...