---
- name: 'Run kubeadm init'
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      sudo kubeadm init --kubernetes-version v{{ kubernetes_version }} --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU,Mem
    executable: /bin/bash
  changed_when: false

- name: 'Pause 30 seconds'
  ansible.builtin.pause:
    seconds: 30

- name: "Make the /home/{{ svc_acct_name }}/.kube directory"
  ansible.builtin.file:
    path: "/home/{{ svc_acct_name }}/.kube"
    state: directory
    owner: "{{ svc_acct_name }}"
    group: "{{ svc_acct_name }}"
    mode: "0700"
  become: false

- name: 'Copy admin.conf to /home/{{ svc_acct_name }}/.kube/config'
  ansible.builtin.copy:
    remote_src: true
    src: '/etc/kubernetes/admin.conf'
    dest: "/home/{{ svc_acct_name }}/.kube/config"
    owner: "{{ svc_acct_name }}"
    group: "{{ svc_acct_name }}"
    mode: '0600'

- name: "Copy manifest files over to /home/{{ svc_acct_name }}/"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ svc_acct_name }}/{{ item }}"
    owner: "{{ svc_acct_name }}"
    group: "{{ svc_acct_name }}"
    mode: '0600'
  loop:
    - 'kube-flannel.yml'

- name: 'Apply the manifests'
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      kubectl create -f /home/{{ svc_acct_name }}/kube-flannel.yml
    executable: /bin/bash
  changed_when: false
  vars:
    ansible_become: false

- name: 'Pause 1 min for creation'
  ansible.builtin.pause:
    minutes: 1

- name: 'Get output of kubectl get nodes'
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      kubectl get nodes -A -o wide
    executable: /bin/bash
  changed_when: false
  register: _get_nodes
  vars:
    ansible_become: false

- name: 'Validate that control node is ready'
  ansible.builtin.assert:
    that: "'Ready' in _get_nodes.stdout"

- name: 'Download the helm binary'
  ansible.builtin.get_url:
    url: 'https://get.helm.sh/helm-v3.15.3-linux-amd64.tar.gz'
    dest: '/var/tmp/'
    validate_certs: false

- name: 'Extract the archive'
  ansible.builtin.unarchive:
    src: '/var/tmp/helm-v3.15.3-linux-amd64.tar.gz'
    dest: '/var/tmp/'
    remote_src: true

- name: 'Copy the helm binary to /usr/bin'
  ansible.builtin.copy:
    src: '/var/tmp/linux-amd64/helm'
    dest: '/usr/bin/helm'
    remote_src: true
    mode: '0755'

- name: 'Get the kubeadm join command'
  ansible.builtin.shell: "kubeadm token create --print-join-command"
  register: _join_command
  vars:
    ansible_become: false

- name: 'Display join command'
  ansible.builtin.pause:
    prompt: |
      IMPORTANT!  Copy the following join command value and keep to use later on to join nodes to the cluster.
      
      JOIN COMMAND: {{ _join_command.stdout }}"
...
