---
# - name: 'Update hostname'
#   ansible.builtin.hostname:
#     name: "{{ _hostname }}"

# - name: 'Update /etc/hosts'
#   ansible.builtin.blockinfile:
#     path: /etc/hosts
#     block: |
#       {{ _c1_cp1_ip }} c1-cp1.example.com c1-cp1
#       {{ _node1_ip }} c1-node1.example.com c1-node1
#       {{ _node2_ip }} c1-node2.example.com c1-node2
#       {{ _node3_ip }} c1-node3.example.com c1-node3

# - name: 'Add k8s io apt repository gpg key this will likely change for each version of kubernetes release'
#   ansible.builtin.shell:
#     cmd: |
#       set -o pipefail
#       curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version_short }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
#     executable: /bin/bash
#   args:
#     creates: '/etc/apt/keyrings/kubernetes-apt-keyring.gpg'
#   changed_when: false

# - name: 'Add the Kubernetes apt repository'
#   ansible.builtin.shell: 
#     cmd: |
#       set -o pipefail
#       echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version_short }}/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
#     executable: /bin/bash
#   args:
#     creates: '/etc/apt/sources.list.d/kubernetes.list'
#   changed_when: false

# - name: 'Run apt update'
#   ansible.builtin.shell: "apt update -y"

# - name: 'Install kubelet kubeadm and kubectl'
#   ansible.builtin.apt:
#     name:
#       - kubelet
#       - kubeadm
#       - kubectl
#     state: present

# - name: 'Mark packages hold so they are not updated'
#   ansible.builtin.shell:
#     cmd: |
#       set -o pipefail
#       apt-mark hold kubelet kubeadm kubectl containerd
#     executable: /bin/bash
#   changed_when: false
...
