---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-storage
  namespace: elastic-system
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/tmp"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-storage2
  namespace: elastic-system
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/tmp"
