---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: elasticsearch-master
  name: elasticsearch-master-elasticsearch-master-0
  namespace: elastic-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  volumeMode: Filesystem
  storageClassName: local-storage
  volumeName: pv-local-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: elasticsearch-master
  name: elasticsearch-data-quickstart-es-default-0
  namespace: elastic-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  volumeMode: Filesystem
  storageClassName: local-storage
  volumeName: pv-local-storage2
